env:
  browser: true
  es2021: true

root: true

extends:
  - 'eslint:recommended'
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: [error, ignorePackages, { js: always }]
  no-param-reassign: 0